{% set version = "2.0.4" %}

package:
  name: libjpeg-turbo
  version: {{ version }}

source:
  url: https://github.com/libjpeg-turbo/libjpeg-turbo/archive/{{ version }}.tar.gz
  sha256: 7777c3c19762940cff42b3ba4d7cd5c52d1671b39a79532050c85efb99079064

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('libjpeg-turbo', max_pin='x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - cmake
    - make
    - msinttypes  # [win and py<35]
    - yasm
    - jom  # [win]

# test:
#   files:
#     - testorig.jpg
#   commands:
#     - djpeg -dct int -ppm -outfile testout.ppm testorig.jpg

about:
  home: http://www.libjpeg-turbo.org/
  license: IJG, modified 3-clause BSD and zlib
  license_file: LICENSE.md
  summary: IJG JPEG compliant runtime library with SIMD and other optimizations
